function out1 = gpopsdynauto(m,m0,l,d,k,x,y,psi,sigma,gamma,R,gdot)
%GPOPSDYN
%    OUT1 = GPOPSDYN(M,M0,L,D,K,X,Y,PSI,SIGMA,GAMMA,R,GDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    14-Apr-2017 01:44:21

t2 = sin(psi);
t3 = 1.0./l;
t4 = cos(psi);
t5 = tan(gamma);
out1 = [sigma.*(t4-d.*t2.*t3.*t5);sigma.*(t2+d.*t3.*t4.*t5);sigma.*t3.*t5;-(-R+k.*sigma.^2+gdot.*m0.*sigma.*t5.*1.0./cos(gamma).^2)./(m+m0.*t5.^2);gdot];
