function model = tireforce(m,m0,l,d,k,x,y,psi,sigma,gamma,R,gdot)
%TIREFORCE
%    MODEL = TIREFORCE(M,M0,L,D,K,X,Y,PSI,SIGMA,GAMMA,R,GDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Apr-2017 18:48:59

t2 = tan(gamma);
t3 = 1.0./l;
t4 = sigma.^2;
t5 = cos(gamma);
t6 = R-k.*t4;
t7 = t2.*t6;
t8 = 1.0./t5.^2;
t9 = gdot.*m.*sigma.*t8;
t10 = t7+t9;
t11 = t2.^2;
t12 = m0.*t11;
t13 = m+t12;
t14 = 1.0./t13;
model = [-t10.*t14.*(m0-d.*m.*t3)-m.*t2.*t3.*t4.*(d.*t3-1.0),(m0.*t10.*t14+d.*1.0./l.^2.*m.*t2.*t4)./t5];
